// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace _50ShadesOfBurgers
{
	public partial class TabBarController : UITabBarController
	{
		public TabBarController (IntPtr handle) : base (handle)
		{
		}
	}
}
